apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rent
    version: "1.0"
  name: rent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rent
  strategy: {}
  template:
    metadata:
      labels:
        app: rent
    spec:
      containers:
        - name: rent
          image: abdelkader30/rent:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rent
  name: rent
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: rent
  type: LoadBalancer
